### PR TITLE
Support Github Action to Build Images

### PR DESCRIPTION
**Pull request by zsnmwy**
https://github.com/zsnmwy/bili-fav-sniffer/pkgs/container/bili-fav-sniffer

https://github.com/zsnmwy/bili-fav-sniffer/actions/runs/4693318744

### CODE REVIEW

**Comment by zsnmwy** [comment]
Is the [DanmakuFactory-1.63.tar.gz](https://github.com/BarryLiu1995/bili-fav-sniffer/blob/main/libs/DanmakuFactory-1.63.tar.gz) working for arm platforms?

**Comment by zsnmwy** [comment]
you can use the [dockerproxy](https://dockerproxy.com/) to pull images from **ghcr.io.**

**Comment by SummerLiu95** [comment]
> Is the [DanmakuFactory-1.63.tar.gz](https://github.com/BarryLiu1995/bili-fav-sniffer/blob/main/libs/DanmakuFactory-1.63.tar.gz) working for arm platforms?

local image builded on M2 chip MacBook is working fine

**Comment by SummerLiu95** [comment]
> https://github.com/zsnmwy/bili-fav-sniffer/pkgs/container/bili-fav-sniffer
> 
> https://github.com/zsnmwy/bili-fav-sniffer/actions/runs/4693318744

Thanks a lot. It is exactly what I plan to do recently

**Comment by SummerLiu95** [comment]
> you can use the [dockerproxy](https://dockerproxy.com/) to pull images from **ghcr.io.**

I have never use dockerproxy before. I only push image to docker official registry at present. I have read your workflow file docker-image.yml and find it will push image to GitHub Container Registry. Is that right?

**Comment by zsnmwy** [comment]
> > you can use the [dockerproxy](https://dockerproxy.com/) to pull images from **ghcr.io.**
> 
> I have never use dockerproxy before. I only push image to docker official registry at present. I have read your workflow file docker-image.yml and find it will push image to GitHub Container Registry. Is that right?

Yes.
If you want to push the image to the docker hub.
Login to the docker hub before the build and push step.
Add the new tag for the docker hub in the build and push step.

Full detail in the [official docs](https://docs.docker.com/build/ci/github-actions/push-multi-registries/).

**Pull request merged**
